/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaksiRouteImport } from './routes/transaksi'
import { Route as SiapKeluarRouteImport } from './routes/siap-keluar'
import { Route as SerahTerimaKembaliRouteImport } from './routes/serah-terima-kembali'
import { Route as SerahTerimaKeluarRouteImport } from './routes/serah-terima-keluar'
import { Route as SedangDisewaRouteImport } from './routes/sedang-disewa'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as BarangRouteImport } from './routes/barang'
import { Route as IndexRouteImport } from './routes/index'

const TransaksiRoute = TransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)
const SiapKeluarRoute = SiapKeluarRouteImport.update({
  id: '/siap-keluar',
  path: '/siap-keluar',
  getParentRoute: () => rootRouteImport,
} as any)
const SerahTerimaKembaliRoute = SerahTerimaKembaliRouteImport.update({
  id: '/serah-terima-kembali',
  path: '/serah-terima-kembali',
  getParentRoute: () => rootRouteImport,
} as any)
const SerahTerimaKeluarRoute = SerahTerimaKeluarRouteImport.update({
  id: '/serah-terima-keluar',
  path: '/serah-terima-keluar',
  getParentRoute: () => rootRouteImport,
} as any)
const SedangDisewaRoute = SedangDisewaRouteImport.update({
  id: '/sedang-disewa',
  path: '/sedang-disewa',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const BarangRoute = BarangRouteImport.update({
  id: '/barang',
  path: '/barang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barang': typeof BarangRoute
  '/customer': typeof CustomerRoute
  '/kalender': typeof KalenderRoute
  '/kategori': typeof KategoriRoute
  '/laporan': typeof LaporanRoute
  '/pembayaran': typeof PembayaranRoute
  '/pengaturan': typeof PengaturanRoute
  '/sedang-disewa': typeof SedangDisewaRoute
  '/serah-terima-keluar': typeof SerahTerimaKeluarRoute
  '/serah-terima-kembali': typeof SerahTerimaKembaliRoute
  '/siap-keluar': typeof SiapKeluarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barang': typeof BarangRoute
  '/customer': typeof CustomerRoute
  '/kalender': typeof KalenderRoute
  '/kategori': typeof KategoriRoute
  '/laporan': typeof LaporanRoute
  '/pembayaran': typeof PembayaranRoute
  '/pengaturan': typeof PengaturanRoute
  '/sedang-disewa': typeof SedangDisewaRoute
  '/serah-terima-keluar': typeof SerahTerimaKeluarRoute
  '/serah-terima-kembali': typeof SerahTerimaKembaliRoute
  '/siap-keluar': typeof SiapKeluarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barang': typeof BarangRoute
  '/customer': typeof CustomerRoute
  '/kalender': typeof KalenderRoute
  '/kategori': typeof KategoriRoute
  '/laporan': typeof LaporanRoute
  '/pembayaran': typeof PembayaranRoute
  '/pengaturan': typeof PengaturanRoute
  '/sedang-disewa': typeof SedangDisewaRoute
  '/serah-terima-keluar': typeof SerahTerimaKeluarRoute
  '/serah-terima-kembali': typeof SerahTerimaKembaliRoute
  '/siap-keluar': typeof SiapKeluarRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barang'
    | '/customer'
    | '/kalender'
    | '/kategori'
    | '/laporan'
    | '/pembayaran'
    | '/pengaturan'
    | '/sedang-disewa'
    | '/serah-terima-keluar'
    | '/serah-terima-kembali'
    | '/siap-keluar'
    | '/transaksi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barang'
    | '/customer'
    | '/kalender'
    | '/kategori'
    | '/laporan'
    | '/pembayaran'
    | '/pengaturan'
    | '/sedang-disewa'
    | '/serah-terima-keluar'
    | '/serah-terima-kembali'
    | '/siap-keluar'
    | '/transaksi'
  id:
    | '__root__'
    | '/'
    | '/barang'
    | '/customer'
    | '/kalender'
    | '/kategori'
    | '/laporan'
    | '/pembayaran'
    | '/pengaturan'
    | '/sedang-disewa'
    | '/serah-terima-keluar'
    | '/serah-terima-kembali'
    | '/siap-keluar'
    | '/transaksi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarangRoute: typeof BarangRoute
  CustomerRoute: typeof CustomerRoute
  KalenderRoute: typeof KalenderRoute
  KategoriRoute: typeof KategoriRoute
  LaporanRoute: typeof LaporanRoute
  PembayaranRoute: typeof PembayaranRoute
  PengaturanRoute: typeof PengaturanRoute
  SedangDisewaRoute: typeof SedangDisewaRoute
  SerahTerimaKeluarRoute: typeof SerahTerimaKeluarRoute
  SerahTerimaKembaliRoute: typeof SerahTerimaKembaliRoute
  SiapKeluarRoute: typeof SiapKeluarRoute
  TransaksiRoute: typeof TransaksiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaksi': {
      id: '/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof TransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siap-keluar': {
      id: '/siap-keluar'
      path: '/siap-keluar'
      fullPath: '/siap-keluar'
      preLoaderRoute: typeof SiapKeluarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serah-terima-kembali': {
      id: '/serah-terima-kembali'
      path: '/serah-terima-kembali'
      fullPath: '/serah-terima-kembali'
      preLoaderRoute: typeof SerahTerimaKembaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serah-terima-keluar': {
      id: '/serah-terima-keluar'
      path: '/serah-terima-keluar'
      fullPath: '/serah-terima-keluar'
      preLoaderRoute: typeof SerahTerimaKeluarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedang-disewa': {
      id: '/sedang-disewa'
      path: '/sedang-disewa'
      fullPath: '/sedang-disewa'
      preLoaderRoute: typeof SedangDisewaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barang': {
      id: '/barang'
      path: '/barang'
      fullPath: '/barang'
      preLoaderRoute: typeof BarangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarangRoute: BarangRoute,
  CustomerRoute: CustomerRoute,
  KalenderRoute: KalenderRoute,
  KategoriRoute: KategoriRoute,
  LaporanRoute: LaporanRoute,
  PembayaranRoute: PembayaranRoute,
  PengaturanRoute: PengaturanRoute,
  SedangDisewaRoute: SedangDisewaRoute,
  SerahTerimaKeluarRoute: SerahTerimaKeluarRoute,
  SerahTerimaKembaliRoute: SerahTerimaKembaliRoute,
  SiapKeluarRoute: SiapKeluarRoute,
  TransaksiRoute: TransaksiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
